name: ci
on:
  push: {}
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  wasm:
    runs-on: ubuntu-latest
    env:
      version: wasm32-wasi-9.8.0.20230927
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        ghcup config add-release-channel https://raw.githubusercontent.com/haskell/ghcup-metadata/develop/ghcup-cross-0.0.8.yaml
        cabal update
    - name: Install WASM toolchain
      run: |
        git clone https://gitlab.haskell.org/ghc/ghc-wasm-meta.git
        cd ghc-wasm-meta/
        export SKIP_GHC=yes
        ./setup.sh
        source ~/.ghc-wasm/env
        ~/.ghc-wasm/add_to_github_path.sh
        cd ..
        ghcup install ghc --set ${{ env.version }} -- --host=x86_64-linux --with-intree-gmp --with-system-libffi
    - name: Build
      run: |
        mv cabal.project.wasi cabal.project.local
        cabal --with-compiler=wasm32-wasi-ghc --with-hc-pkg=wasm32-wasi-ghc-pkg build
        cabal --with-compiler=wasm32-wasi-ghc --with-hc-pkg=wasm32-wasi-ghc-pkg list-bin test:bitvec-tests --enable-tests
        wasmtime $(cabal --with-compiler=wasm32-wasi-ghc --with-hc-pkg=wasm32-wasi-ghc-pkg list-bin test:bitvec-tests --enable-tests)
