name: ci
on:
  push:
    branches:
      - master
      - ci-emulated
  pull_request: {}

defaults:
  run:
    shell: bash

jobs:
  emulated:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: ['s390x', 'ppc64le', 'armv7', 'aarch64']
    steps:
    - uses: actions/checkout@v3
    - uses: uraimo/run-on-arch-action@v2
      timeout-minutes: 60
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu22.04
        githubToken: ${{ github.token }}
        install: |
          apt-get update -y
          apt-get install -y ghc libghc-vector-dev libghc-tasty-quickcheck-dev libghc-tasty-hunit-dev
        run: |
          ghc --version
          echo "#define BOUNDS_CHECK(f) (\_ _ _ -> id)" > src/vector.h
          echo "#define UNSAFE_CHECK(f) (\_ _ _ -> id)" >> src/vector.h
          ghc --make -Isrc:test -isrc:test -o Tests test/Main.hs +RTS -s
          ./Tests +RTS -s
          ghc --make -Isrc:test -isrc:test -DUseSIMD -o Tests test/Main.hs +RTS -s
          ./Tests +RTS -s
